---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---
## 網站資料爬取
```{r}
##這是R Code Chunk
##第一次使用要先安裝 install.packages("rvest")
##read_html
##html_nodes
##html_text
##install.packages("rvest")
library(rvest)
PPT<- "https://www.ptt.cc/bbs/Tech_Job/index.html"
postTitle<- read_html(PPT) %>%
html_nodes(".title") %>%
html_text()
postPushNum<- read_html(PPT) %>%
html_nodes(".nrec") %>%
html_text()
postAuthor<- read_html(PPT) %>%
html_nodes(".author") %>%
html_text()
df1<- data.frame(Title=postTitle,PushNum=postPushNum,Author=postAuthor)
PPT<- "https://www.ptt.cc/bbs/Tech_Job/index2588.html"
postTitle<- read_html(PPT) %>%
html_nodes(".title") %>%
html_text()
postPushNum<- read_html(PPT) %>%
html_nodes(".nrec") %>%
html_text()
postAuthor<- read_html(PPT) %>%
html_nodes(".author") %>%
html_text()
df2<- data.frame(Title=postTitle,PushNum=postPushNum,Author=postAuthor)
PPT<- "https://www.ptt.cc/bbs/Tech_Job/index2587.html"
postTitle<- read_html(PPT) %>%
html_nodes(".title") %>%
html_text()
postPushNum<- read_html(PPT) %>%
html_nodes(".nrec") %>%
html_text()
postAuthor<- read_html(PPT) %>%
html_nodes(".author") %>%
html_text()
df3<- data.frame(Title=postTitle,PushNum=postPushNum,Author=postAuthor)
PPT<- "https://www.ptt.cc/bbs/Tech_Job/index2586.html"
postTitle<- read_html(PPT) %>%
html_nodes(".title") %>%
html_text()
postPushNum<- read_html(PPT) %>%
html_nodes(".nrec") %>%
html_text()
postAuthor<- read_html(PPT) %>%
html_nodes(".author") %>%
html_text()
df4<- data.frame(Title=postTitle,PushNum=postPushNum,Author=postAuthor)
PPT<- "https://www.ptt.cc/bbs/Tech_Job/index2585.html"
postTitle<- read_html(PPT) %>%
html_nodes(".title") %>%
html_text()
postPushNum<- read_html(PPT) %>%
html_nodes(".nrec") %>%
html_text()
postAuthor<- read_html(PPT) %>%
html_nodes(".author") %>%
html_text()
df5<- data.frame(Title=postTitle,PushNum=postPushNum,Author=postAuthor)
PPT<- "https://www.ptt.cc/bbs/Tech_Job/index2584.html"
postTitle<- read_html(PPT) %>%
html_nodes(".title") %>%
html_text()
postPushNum<- read_html(PPT) %>%
html_nodes(".nrec") %>%
html_text()
postAuthor<- read_html(PPT) %>%
html_nodes(".author") %>%
html_text()
df6<- data.frame(Title=postTitle,PushNum=postPushNum,Author=postAuthor)
total<- rbind(df1,df2,df3,df4,df5,df6)
total
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(total) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
#這是R Code Chunk
nrow(total)
##總共有110篇文章，其中最多文章是請教別人問題的文章；或者是發一些有關工作的新聞
```

解釋解釋解釋解釋

```{r}
#這是R Code Chunk
table(total$Author)
##每個作者的發文數都差不多都只有一篇或兩篇，被刪文的有16篇
```

解釋解釋解釋解釋

人工結論與解釋解釋解釋解釋解釋解釋解釋

雖然在PTT上問問題的人很多，但是這種文章通常都不太會有推文數，反而是其他公告事情或是新聞的文章，比較多人關注
